//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Redes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Redes()
        {
            this.Enlaces = new HashSet<Enlaces>();
        }
    
        public int IdRed { get; set; }
        public string Linea { get; set; }
        public string Gateway { get; set; }
        public string Interface { get; set; }
        public string TipoEnlace { get; set; }
        public string Bandwidth { get; set; }
        public string MedioEnlace { get; set; }
        public string Comentario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enlaces> Enlaces { get; set; }
    }
}
