//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles_Permisos
    {
        public int IdPermiso { get; set; }
        public Nullable<int> Id_Rol { get; set; }
        public Nullable<int> Modulo { get; set; }
        public string Agregar { get; set; }
        public string Modificar { get; set; }
        public string Eliminar { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
