CREATE TABLE [dbo].Redes
(
  	 IdRed INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Redes PRIMARY KEY CLUSTERED(IdRed)
	, Linea VARCHAR(25) NOT NULL
	, Gateway VARCHAR(25) NOT NULL
	, Interface VARCHAR(100) NOT NULL
    , TipoEnlace VARCHAR(100) NOT NULL
    , Bandwidth VARCHAR(25) NOT NULL
    , MedioEnlace VARCHAR(100) NOT NULL
    , Comentario VARCHAR(500) NULL  
)WITH (DATA_COMPRESSION = PAGE)
