CREATE TABLE [dbo].Roles
(
	  IdRol INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Roles PRIMARY KEY CLUSTERED (IdRol)
    , Rol VARCHAR(50) NOT NULL
	, Descripcion VARCHAR(200) NOT NULL
	, Estado BIT NOT NULL 
		CONSTRAINT DF_Roles_Estado DEFAULT(0)
)WITH (DATA_COMPRESSION = PAGE)
