CREATE TABLE [dbo].Usuarios
(
  IdUsuario INT NOT NULL IDENTITY(1,1) 
	        CONSTRAINT PK_Usuario PRIMARY KEY CLUSTERED (IdUsuario)
 	, IdRol INT NOT NULL 
		CONSTRAINT FK_Usuarios_Roles FOREIGN KEY(IdRol) REFERENCES dbo.Roles(IdRol)
	, Identificacion VARCHAR (9) NOT NULL
	, Nombre VARCHAR(50) NOT NULL
	, Telefono VARCHAR(10) NOT NULL
	, Email  VARCHAR(50) NOT NULL
	, Usuario VARCHAR(50) NOT NULL
	, Contrasena VARCHAR(50) NOT NULL
    , Estado BIT NOT NULL 
		CONSTRAINT DF_Usuarios_Estado DEFAULT(0)
)WITH (DATA_COMPRESSION = PAGE)

